### ISSUE TITLE
Add to config.yml links to each Google Form for each language

### ISSUE THREAD

**Issue by avancevl** [avancevl/avancevl.github.io#11]

**Comment by jq153387** [comment]
![image_20200602102618](https://user-images.githubusercontent.com/11733606/83473195-8e368a00-a4bb-11ea-8ee5-945b98ca6bd5.png)
![image_20200602102223](https://user-images.githubusercontent.com/11733606/83473204-9262a780-a4bb-11ea-8038-24809d91bf5f.png)
