### ISSUE TITLE
Language button

### ISSUE THREAD

**Issue by DanielChen1013** [avancevl/avancevl.github.io#14]
Instead of text for the language button, please replace with a recognizable icon.

<img width="1430" alt="Screen Shot 2020-05-20 at 11 07 07 AM" src="https://user-images.githubusercontent.com/14017691/82400578-43b01900-9a8a-11ea-974f-5cc2b6ef82e6.png">
<img width="48" alt="Screen Shot 2020-05-20 at 11 08 57 AM" src="https://user-images.githubusercontent.com/14017691/82400601-50347180-9a8a-11ea-9b9b-12007ae28587.png">

**Comment by jq153387** [comment]
![image_20200521171848](https://user-images.githubusercontent.com/11733606/82619014-4a17cf80-9c07-11ea-88b5-d2b54da1d464.png)
![image_20200521171802](https://user-images.githubusercontent.com/11733606/82619015-4b48fc80-9c07-11ea-8a98-226f1484aa9d.png)

**Comment by avancevl** [comment]
💯
