### ISSUE TITLE
Right side menu

### ISSUE THREAD

**Issue by DanielChen1013** [avancevl/avancevl.github.io#15]
Menu:

1. make wider
2. move to the right more

<img width="1435" alt="Screen Shot 2020-05-20 at 11 07 38 AM" src="https://user-images.githubusercontent.com/14017691/82400659-7b1ec580-9a8a-11ea-9d55-df8f38408c9e.png">

**Comment by jq153387** [comment]
![未命名-1](https://user-images.githubusercontent.com/11733606/82626208-cddab780-9c19-11ea-998d-01535c930c04.png)
![image_20200522102458](https://user-images.githubusercontent.com/11733606/82626210-cf0be480-9c19-11ea-9ad4-8e02f583f492.png)
![image_20200522101312](https://user-images.githubusercontent.com/11733606/82626212-cf0be480-9c19-11ea-8908-4e83ae4e723a.png)
![image_20200522101252](https://user-images.githubusercontent.com/11733606/82626213-cfa47b00-9c19-11ea-8074-e83836a540d2.png)
![image_20200522101240](https://user-images.githubusercontent.com/11733606/82626215-d03d1180-9c19-11ea-9a6e-45292e962abd.png)

**Comment by avancevl** [comment]
:100:
