### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by DanielChen1013** [avancevl/avancevl.github.io#16]
Mobile menu
1. default should be collapsed (like desktop)
2. arrows should be on the right (like desktop)
3. some lines have extra indent space in the front

<img width="302" alt="Screen Shot 2020-05-21 at 8 20 36 PM" src="https://user-images.githubusercontent.com/14017691/82558602-9c71d580-9ba0-11ea-95fa-a9a4464518e0.png">

**Comment by jq153387** [comment]
![image_20200522105006](https://user-images.githubusercontent.com/11733606/82626303-0da19f00-9c1a-11ea-96cf-bd1c1a383657.png)

**Comment by avancevl** [comment]
💯
