### ISSUE TITLE
All navigation titles need to be left aligned

### ISSUE THREAD

**Issue by avancevl** [avancevl/avancevl.github.io#17]
![image](https://user-images.githubusercontent.com/58037887/82578905-9ccd9900-9bbf-11ea-94ec-3618b423ea36.jpeg)

**Comment by jq153387** [comment]
![image_20200522105006](https://user-images.githubusercontent.com/11733606/82626303-0da19f00-9c1a-11ea-96cf-bd1c1a383657.png)

**Comment by avancevl** [comment]
💯
