### ISSUE TITLE
Mobile menu clickable area

### ISSUE THREAD

**Issue by DanielChen1013** [avancevl/avancevl.github.io#18]
User can click on each section (empty place in each row/section) to go to that section, not just the text.

<img width="297" alt="Screen Shot 2020-05-22 at 11 58 28 AM" src="https://user-images.githubusercontent.com/14017691/82629864-8eb16400-9c23-11ea-94d1-fc681b8e027f.png">

**Comment by avancevl** [comment]
![image](https://user-images.githubusercontent.com/58037887/82633130-f28c5a80-9c2c-11ea-875d-4185545bd65c.jpeg)

Larger clickable area

**Comment by avancevl** [comment]
:100:
