### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by DanielChen1013** [avancevl/avancevl.github.io#21]
1. arrow 大一點
2. 多餘的空格 （被擠出來的）

![IMG_3223](https://user-images.githubusercontent.com/14017691/82727152-4ecda800-9d1b-11ea-90b0-3532222ad096.jpg)

**Comment by jq153387** [comment]
![image_20200527093616](https://user-images.githubusercontent.com/11733606/82966846-61d3c700-9ffe-11ea-9e0c-885e2b31dd33.png)

**Comment by DanielChen1013** [comment]
選擇子子頁面，前面menu還是有多餘的空格，被擠出來的

**Comment by jq153387** [comment]
fixed.

![image_20200527144902](https://user-images.githubusercontent.com/11733606/82987081-8b561800-a029-11ea-8c83-91857459f4e3.png)
![image_20200527144941](https://user-images.githubusercontent.com/11733606/82987082-8c874500-a029-11ea-8b8a-ee829d0198d6.png)

**Comment by DanielChen1013** [comment]
還有：
在任何一個母頁的時候，按menu，那個母頁的 子menu 需要展開。
在任何一個子頁的時候，按menu，那個子頁的 子子menu 需要展開。

**Comment by DanielChen1013** [comment]
這個 menu behavior 在 desktop 也需要有一樣的

**Comment by DanielChen1013** [comment]
我在 dekstop 和 mobile 沒有看到:

在任何一個母頁 page 的時候，那個母頁的 子menu sub-page 需要是已經展開 expanded。
在任何一個子頁 page 的時候，那個子頁的 子子menu sub-page需是已經展開 expanded。

現在： 
<img width="214" alt="Screen Shot 2020-06-03 at 11 10 29 AM" src="https://user-images.githubusercontent.com/14017691/83591574-d83a7100-a58a-11ea-87a1-c509399bf2dc.png">

應該要是：
<img width="236" alt="Screen Shot 2020-06-03 at 11 10 40 AM" src="https://user-images.githubusercontent.com/14017691/83591590-dffa1580-a58a-11ea-9cb0-1d5e82551b33.png">

**Comment by DanielChen1013** [comment]
👍
