### ISSUE TITLE
RWD not working

### ISSUE THREAD

**Issue by DanielChen1013** [avancevl/avancevl.github.io#23]
這頁沒有 mobile RWD 

<img width="338" alt="Screen Shot 2020-06-02 at 11 33 13 AM" src="https://user-images.githubusercontent.com/14017691/83591755-3f582580-a58b-11ea-8f73-6777508ca059.png">

**Comment by jq153387** [comment]
<img width="317" alt="截圖 2020-07-24 下午1 58 54" src="https://user-images.githubusercontent.com/11733606/88364608-fddb3e00-cdb5-11ea-8297-4231a2ec9b45.png">

use Responsive Table

**Comment by DanielChen1013** [comment]
💯
