### ISSUE TITLE
Please check whether the metadata format of the .md file is correct

### ISSUE THREAD

**Issue by jq153387** [avancevl/avancevl.github.io#25]
## Metadata format

Please check whether the metadata format of the .md file is correct, and tab symbols cannot be used in the metadata

<img width="818" alt="截圖 2021-03-22 上午10 31 19" src="https://user-images.githubusercontent.com/11733606/111937563-f44fd480-8b02-11eb-9842-f4319669f11e.png">

<img width="1291" alt="截圖 2021-03-22 上午10 32 08" src="https://user-images.githubusercontent.com/11733606/111937593-06317780-8b03-11eb-8d63-5c741797eb04.png">

## How to use VSCode edit convert indentation to spaces

<img width="1252" alt="截圖 2021-03-22 上午10 34 20 1" src="https://user-images.githubusercontent.com/11733606/111937651-282afa00-8b03-11eb-857c-3273d7666efa.png">

**Comment by JangkarBumi** [comment]
Got it. Thanks!
