### ISSUE TITLE
Add exam links back into TOC

### ISSUE THREAD

**Issue by avancevl** [avancevl/avancevl.github.io#3]
![Screen Shot 2020-05-13 at 2 05 10 PM](https://user-images.githubusercontent.com/58037887/81779825-0e567900-9528-11ea-98b9-d29d13b5bc89.png)

**Comment by jq153387** [comment]
<img width="245" alt="截圖 2020-05-19 下午8 31 08" src="https://user-images.githubusercontent.com/11733606/82326920-276f9600-9a10-11ea-866c-9728a75d4c4c.png">

**Comment by avancevl** [comment]
:100:
