### ISSUE TITLE
Make "AVL" in footer into a configurable variable in language.yml

### ISSUE THREAD

**Issue by avancevl** [avancevl/avancevl.github.io#4]
![Screen Shot 2020-05-13 at 9 16 12 AM](https://user-images.githubusercontent.com/58037887/81779910-33e38280-9528-11ea-90db-31282af9205d.png)

**Comment by jq153387** [comment]
![image_20200514100620](https://user-images.githubusercontent.com/11733606/81884606-e4a25e00-95ca-11ea-8930-13e55d3fd951.png)
![image_20200514100658](https://user-images.githubusercontent.com/11733606/81884602-e1a76d80-95ca-11ea-8ac5-7d45211cb8ef.png)

**Comment by avancevl** [comment]
:100:
