### ISSUE TITLE
When <a> for lang is missing, generate blank page and fix broken URL

### ISSUE THREAD

**Issue by avancevl** [avancevl/avancevl.github.io#6]
Example of broken URL:

https://avancevl.github.io/zh-cn/announcemzh-cnts

**Comment by avancevl** [comment]
Run this app after fix to check for broken links.

https://ahrefs.com/broken-link-checker

**Comment by avancevl** [comment]
Please add placeholder "TODO" for the blank pages, so we can grep "TODO" and easily find these blank pages.

**Comment by jq153387** [comment]
<img width="572" alt="截圖 2020-05-18 下午9 09 06" src="https://user-images.githubusercontent.com/11733606/82217383-e95d6e00-994c-11ea-9647-26947aceaf9b.png">

<img width="986" alt="截圖 2020-05-18 下午9 16 11" src="https://user-images.githubusercontent.com/11733606/82217389-ec585e80-994c-11ea-9fc1-df25f8ee52b4.png">

<img width="887" alt="截圖 2020-05-18 下午9 10 10" src="https://user-images.githubusercontent.com/11733606/82217391-ed898b80-994c-11ea-8e1e-0da9b5cb3b87.png">

**Comment by avancevl** [comment]
:+1:
