### ISSUE TITLE
Add more space above footer's horizontal line

### ISSUE THREAD

**Issue by avancevl** [avancevl/avancevl.github.io#8]
![Screen Shot 2020-05-13 at 2 47 53 PM](https://user-images.githubusercontent.com/58037887/81780220-c1bf6d80-9528-11ea-9109-5a16ce86fd23.png)

**Comment by jq153387** [comment]
![image_20200514110520](https://user-images.githubusercontent.com/11733606/81887930-d2c4b900-95d2-11ea-8902-7b36f62afda2.png)

**Comment by avancevl** [comment]
:100:
