### ISSUE TITLE
Generate a copy of the "default" language pages so that all the old links work

### ISSUE THREAD

**Issue by avancevl** [avancevl/avancevl.github.io#9]

**Comment by avancevl** [comment]
Let's say "en" is default language. i18.py script will copy (not move) all markdown files so that:

avancevl.github.io/en/index.md --> is copied / same as avancevl.github.io/index.md

e.g. 

avancevl.github.io/en/engineering/tech_stack --> is copied / same as avancevl.github.io/engineering/tech_stack

**Comment by jq153387** [comment]
![image_20200518095053](https://user-images.githubusercontent.com/11733606/82167066-22fe8c80-98ed-11ea-88bd-c0a7b4ad4011.png)

The _confing.yml file can set default lang.  Run i18n.py file will copy default language index.md file to "./index.md".

**Comment by avancevl** [comment]
On the default https://avancevl.github.io/ index page, the "Language" dropdown does not work.

**Comment by jq153387** [comment]
It has been fixed.

**Comment by avancevl** [comment]
👍
